#!/usr/bin/env bash
console_func () 
{ 
    builtin unset -v console_args console_prompt;
    builtin typeset console_args="$*" console_prompt="${console_file##*/}";
    [[ -n "$console_args" || "$console_interactive" -eq 0 ]] || { 
        if [[ -n "$KSH_VERSION" ]]; then
            console_args="$(command fzf --prompt=":${console_prompt} " --print-query <<< "")";
        else
            command tput sc;
            command tput cup 99999 0;
            if [[ -n "$ZSH_VERSION" ]]; then
                builtin vared -p ":${console_prompt} " console_args;
            else
                builtin read -re -p ":${console_prompt} " console_args;
            fi;
            command tput rc;
            command tput ed;
        fi
    };
    builtin set -- ${console_args};
    (($# > 0)) && { 
        __fzffs_util_parse_flags "$*" && builtin shift 1;
        __fzffs_util_parse_macros "$*"
    };
    if [[ "$console_terminal" == "console_terminal" ]]; then
        if [[ "$console_fork_background" == "console_fork_background" ]]; then
            ( builtin eval ${TERMINAL} -e "${console_args}\;${console_keep:+${SHELL:-sh}}" \& );
        else
            builtin eval ${TERMINAL} -e "${console_args}\;${console_keep:+${SHELL:-sh}}";
        fi;
    else
        if [[ "$console_fork_background" == "console_fork_background" ]]; then
            ( builtin eval ${SHELL:-sh} "${console_args:+-c $console_args}" \& );
        else
            builtin eval ${SHELL:-sh} "${console_args:+-c $console_args}" ${console_keep:+\; command printf '%s\\n' \'Press ENTER to continue\' ; builtin read};
        fi;
    fi
}
